spin_manifest_version = 2

[application]
name = "vita"
version = "0.1.0"
authors = ["Alessandro Cifani <alessandro.cifani@gmail.com>"]
description = ""

[variables]
local_id = { required = true }

[application.trigger.redis]
address = "redis://localhost:6379"

[[trigger.redis]]
channel = "universe"
component = "vita-wasi"

[component.vita-wasi]
source = "./multiverse/wasi.wasm"
allowed_outbound_hosts = ["redis://localhost:6379"]
[component.vita-wasi.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o ./multiverse/wasi.wasm ./multiverse/wasi.go"
watch = ["**/*.go", "go.mod"]
[component.vita-wasi.variables]
local_id = "{{ local_id }}"
redis_host = "redis://localhost:6379"
