spin_manifest_version = 2

[application]
name = "vita"
version = "0.1.0"
authors = ["Alessandro Cifani <alessandro.cifani@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "vita"

[component.vita]
source = "./wasi/vita.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]
[component.vita.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o ./wasi/vita.wasm ./wasi/run.go"
