spin_manifest_version = "1"
authors = ["Alessandro Cifani <alessandro.cifani@gmail.com>"]
name = "vita"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "vita"
source = "./wasi/vita.wasm"
key_value_stores = ["default"]
[component.trigger]
route = "/..."
[component.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o ./wasi/vita.wasm ./wasi/run.go"
