name: Build and deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup tinygo
        uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: 0.30.0

      - name: build
        run: make build_tinygo

      - name: deploy to gh pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
